version: "3.8"

services:

  scrapydweb:
    image: bardusco/scrapy-platform
    command: scrapydweb
    ports:
      - "5000:5000"
    volumes:
      - scrapyd-data:/app/scrapyd
      - scrapydweb-data:/app/scrapydweb
    environment:
      - PASSWORD
      - USERNAME
      - SCRAPYD_SERVERS
      - TELEGRAM_TOKEN
      - TELEGRAM_CHAT_ID
    restart: unless-stopped

  scrapyd:
    image: bardusco/scrapy-platform
    command: scrapyd
    ports:
      - "6800:6800"
    volumes:
      - scrapyd-data:/app/scrapyd
    environment:
      - SPLASH_URL
      - WEBHOOK_URL
      - SCRAPYDWEB_URL
      - USERNAME
      - PASSWORD
      - TELEGRAM_CHAT_ID
    restart: unless-stopped

  splash:
    image: whalebothelmsman/splash
    ports:
      - "8050:8050"
    restart: unless-stopped

volumes:
  scrapyd-data:
  scrapydweb-data:
