version: "3.8"

services:

  scrapydweb:
    image: bardusco/scrapy-platform
    container_name: scrapydweb
    command: scrapydweb
    ports:
      - "5000:5000"
    volumes:
      - scrapyd-data:/app/scrapyd
      - scrapydweb-data:/app/scrapydweb
    environment:
      - PASSWORD
      - USERNAME
      - SCRAPYD_SERVERS
      - SCRAPYD_USERNAME
      - SCRAPYD_PASSWORD
      - TELEGRAM_TOKEN
      - TELEGRAM_CHAT_ID
    restart: unless-stopped

  scrapyd:
    image: bardusco/scrapy-platform
    container_name: scrapyd
    entrypoint: ["/app/scrapyd-config-setup.sh"]
    command: scrapyd
    ports:
      - "6800:6800"
    volumes:
      - scrapyd-data:/app/scrapyd
    environment:
      - PASSWORD
      - PROXY_HOST
      - PROXY_PASS
      - PROXY_USER
      - SCRAPYD_PASS_DEV
      - SCRAPYD_PASS_PROD
      - SCRAPYD_PASSWORD
      - SCRAPYD_PROJECT_DEV
      - SCRAPYD_PROJECT_PROD
      - SCRAPYD_SERVERS
      - SCRAPYD_URL_DEV
      - SCRAPYD_URL_PROD
      - SCRAPYD_USER_DEV
      - SCRAPYD_USERNAME
      - SCRAPYD_USER_PROD
      - SCRAPYDWEB_URL
      - SPLASH_URL
      - TELEGRAM_CHAT_ID
      - USERNAME
      - WEBHOOK_URL
    restart: unless-stopped

volumes:
  scrapyd-data:
  scrapydweb-data:
